apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: mtv-live-migration
  name: mtv-live-migration
  namespace: kube-system
type: kubernetes.io/service-account-token
