- ansible.builtin.import_tasks: example/delete.yml
  tags: osvirt_example_workload

- name: Delete custom storageprofiles
  kubernetes.core.k8s:
    template:
      - storageprofiles/efs-csi-storageprofile.yaml
      - storageprofiles/iscsi-target-storageprofile.yaml
      - storageprofiles/local-hostpath-storageprofile.yaml
      - storageprofiles/lvms-loop1-vg-storageprofile.yaml
      - storageprofiles/nfs-csi-storageprofile.yaml
      - storageprofiles/openebs-lvm-storageprofile.yaml
      - storageprofiles/rook-ceph-block-storageprofile.yaml
      - storageprofiles/rook-ceph-block-virtualization-storageprofile.yaml
      - storageprofiles/rook-ceph-delete-bucket-storageprofile.yaml
      - storageprofiles/rook-cephfs-storageprofile.yaml
      - storageprofiles/rook-nfs-storageprofile.yaml
    state: absent
  tags: osvirt_instance

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: kubevirt.io/v1
        kind: VirtualMachine
      - api_version: kubevirt.io/v1
        kind: VirtualMachineInstance

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_delete.yml
  vars:
    autogitops_app_dst_path: openshift-virtualization/live-migration
  tags: osvirt_livemigration

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_delete.yml
  vars:
    autogitops_app_dst_path: openshift-virtualization/hostpath-provisioner
  tags: osvirt_hostpathprov

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: alermanager_silence_manage.yml
  vars:
    oscomm_silence_definition: '{{ lookup("file", "silences/hostpath_provisioner.json", rstrip=false) | from_json }}'
    oscomm_silence_state: absent
  tags: osvirt_hostpathprov

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_delete.yml
  vars:
    autogitops_app_dst_path: openshift-virtualization/instance
  tags: osvirt_instance

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: alermanager_silence_manage.yml
  vars:
    oscomm_silence_definition: '{{ lookup("file", "silences/default_storageclass_degraded.json", rstrip=false) | from_json }}'
    oscomm_silence_state: absent
  tags: osvirt_instance

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_delete.yml
  vars:
    autogitops_app_dst_path: openshift-virtualization/operator
  tags: osvirt_operator

- ansible.builtin.import_tasks: cluster_nodes/delete.yml
  tags: osvirt_cluster_nodes
