- name: Power off
  community.general.redfish_command:
    category: Systems
    command: PowerForceOff
    baseuri: '{{ item.value.bmc.baseuri }}'
    username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    resource_id: '{{ item.value.bmc.resource_id }}'
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

# If using Sushy BMC emulator, ejecting the virtual media detaches the CD-ROM
# drive from the virtual machine which removes the CD-ROM from the boot order.
#
# It is possible to eject the virtual media using the VirtualMediaEject
# of community.general.redfish_command. Unfortunately, this currently requires
# passing the image_url which makes it difficult to use, see also:
# VirtualMediaEject should not require image_url #3042
# https://github.com/ansible-collections/community.general/issues/3042
- name: Eject virtual media
  uri:
    url: https://{{ item.value.bmc.baseuri }}/redfish/v1/Systems/{{ item.value.bmc.resource_id }}/VirtualMedia/Cd/Actions/VirtualMedia.EjectMedia
    method: POST
    url_username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    url_password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    force_basic_auth: true
    validate_certs: false
    status_code: [ 200, 204 ]
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

- name: Insert virtual media
  community.general.redfish_command:
    category: Systems
    command: VirtualMediaInsert
    baseuri: '{{ item.value.bmc.baseuri }}'
    username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    resource_id: '{{ item.value.bmc.resource_id }}'
    virtual_media:
      image_url: '{{ osclusterinstall_info.iso_download_url }}'
      media_types:
        - CD
        - DVD
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

# If using Sushy BMC emulator, inserting the virtual media attaches the CD-ROM
# drive to the virtual machine and marks it as the first drive to boot from.
- name: Set one-time boot from CD-ROM
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    baseuri: '{{ item.value.bmc.baseuri }}'
    username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    resource_id: '{{ item.value.bmc.resource_id }}'
    bootdevice: Cd
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

#  If using Sushy BMC emulator, use the following task to set the boot order:
#  1. Disk
#  2. CD-ROM
#
#  Sushy BMC emulator can't set the one-time boot order. Instead, it sets the
#  boot order permanently. When using Sushy, set the boot order 1. Disk,
#  2. CD-ROM, and erase the disk prior to the OpenShift installation. This
#  ensures that the first boot happens from the CD-ROM (as the disk has no
#  operating system on it) and all the following boots use the disk.
#
#  If not using Sushy, comment out the following code to keep the one-time boot
#  from CD-ROM:
- name: Set one-time boot from disk
  community.general.redfish_command:
    category: Systems
    command: SetOneTimeBoot
    baseuri: '{{ item.value.bmc.baseuri }}'
    username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    resource_id: '{{ item.value.bmc.resource_id }}'
    bootdevice: Hdd
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'

- name: Power on
  community.general.redfish_command:
    category: Systems
    command: PowerOn
    baseuri: '{{ item.value.bmc.baseuri }}'
    username: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.username }}'
    password: '{{ osclusterinstall_info.cluster_nodes_shared.bmc.password }}'
    resource_id: '{{ item.value.bmc.resource_id }}'
  loop: '{{ osclusterinstall_info.cluster_nodes_individual | dict2items }}'
  loop_control:
    label: '{{ item.key }}'
