{
 "title": "Tekton Overview",
 "description": "This is a dashboard for Tekton.\r\n",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "database", "label": "database", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Now", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running PipelineRun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tekton_pipelines_controller_running_pipelineruns_count)"
    }
   ]
  },
  {
   "title": "Running Taskrun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(tekton_pipelines_controller_running_taskruns_count)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Running Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Running\", namespace=~\"^$namespace$\"}>0)",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Pending Pipelinerun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum by (label_tekton_dev_pipeline_run) (kube_pod_labels{namespace=~\"^$namespace$\", label_tekton_dev_pipeline_run!=\"\"}  and on (pod) kube_pod_container_status_running{namespace=~\"^$namespace$\"} > 0) == 1)",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Runing Pipelinerun",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (namespace, label_tekton_dev_pipeline, label_tekton_dev_pipeline_run, label_tekton_dev_task_run, label_tekton_dev_cluster_task, kubernetes_node, pod) (kube_pod_labels{label_tekton_dev_task_run!=\"\", namespace=~\"^$namespace$\"}  and on (pod) kube_pod_container_status_running > 0)"
    },
    {
     "expr": "sum by (namespace, pod) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=~\"^$namespace$\"}[5m])) and on (pod) (kube_pod_labels{label_tekton_dev_task_run!=\"\", namespace=~\"^$namespace$\"}) and on (pod) kube_pod_container_status_running > 0"
    },
    {
     "expr": "sum by (namespace, pod)(container_memory_working_set_bytes{image!=\"\", namespace=~\"^$namespace$\"}) and on (pod) (kube_pod_labels{label_tekton_dev_task_run!=\"\", namespace=~\"^$namespace$\"}) and on (pod) kube_pod_container_status_running > 0"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Active Clustertask",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (label_tekton_dev_cluster_task) (kube_pod_labels{label_tekton_dev_cluster_task!=\"\"}))"
    }
   ]
  },
  {
   "title": "Active Pipeline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{}))"
    }
   ]
  },
  {
   "title": "Active Pipelinerun",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pipelinerun) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{}))"
    }
   ]
  },
  {
   "title": "Pipelinerun Increase(5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(tekton_pipelines_controller_pipelinerun_count{}[5m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "All Nodes Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo|nodelocaldns|dummy0|cali.*|docker.*|tunl.*|kube.*|veth.*|br.*\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo|nodelocaldns|dummy0|cali.*|docker.*|tunl.*|kube.*|veth.*|br.*\"}[5m]))",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "All Nodes Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total{device!=\"\"}[5m]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{device!=\"\"}[5m]))",
     "legendFormat": "Written"
    },
    {
     "expr": "sum(rate(node_disk_io_time_seconds_total{device!=\"\"}[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Active Cluster Task",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (label_tekton_dev_cluster_task) (kube_pod_labels{label_tekton_dev_cluster_task!=\"\"})",
     "legendFormat": "Totals"
    },
    {
     "expr": " sum by (label_tekton_dev_cluster_task) (sum by (label_tekton_dev_cluster_task, pod) (kube_pod_labels{label_tekton_dev_cluster_task!=\"\"}) and on(pod) kube_pod_status_phase{phase=\"Failed\"}>0)",
     "legendFormat": "Failed"
    },
    {
     "expr": " sum by (label_tekton_dev_cluster_task) (sum by (label_tekton_dev_cluster_task, pod) (kube_pod_labels{label_tekton_dev_cluster_task!=\"\"}) and on(pod) kube_pod_container_status_running>0)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Failed Pipelinerun Recently",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum by (namespace, label_tekton_dev_pipeline, label_tekton_dev_pipeline_run) (kube_pod_labels{label_tekton_dev_pipeline_run!=\"\", namespace=~\"^$namespace$\"}  and on (pod) kube_pod_status_phase{phase=\"Failed\"} > 0)"
    }
   ]
  },
  {
   "title": "TopK  Pipelinerun Duration",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "topk(15, sum by (namespace, pipeline, pipelinerun) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=~\"^$namespace$\"}) )",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "TopK Pipelinerun Count",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "topk(15, count by (namespace, pipeline) (tekton_pipelines_controller_pipelinerun_duration_seconds_sum{namespace=~\"^$namespace$\"}) )"
    }
   ]
  }
 ]
}