- name: Delete etcd-backup Helm chart
  kubernetes.core.helm:
    name: '{{ etcdbackupadfinis_name }}'
    release_namespace: '{{ etcdbackupadfinis_namespace }}'
    wait: true
    state: absent

- name: Delete etcd-backup namespace
  kubernetes.core.k8s:
    template:
      - namespace.yaml
    wait: true
    state: absent
