- name: Retrieve backup job {{ etcdbackupadfinis_namespace }}/etcd-backup-test created by Ansible
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    name: etcd-backup-test
    namespace: '{{ etcdbackupadfinis_namespace }}'
  register: etcdbackupadfinis_job_result

- name: Trigger etcd backup manually
  ansible.builtin.command: |
    oc create job \
      --namespace {{ etcdbackupadfinis_namespace }} \
      --from=cronjob/etcd-backup-openshift-{{ etcdbackupadfinis_name }} \
      etcd-backup-test
  when: etcdbackupadfinis_job_result.resources | length == 0

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for backup to complete
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    name: etcd-backup-test
    namespace: '{{ etcdbackupadfinis_namespace }}'
  register: etcdbackupadfinis_job_result
  until:
    - (etcdbackupadfinis_job_result.resources.0.status.succeeded | default(0) > 0) or
      (etcdbackupadfinis_job_result.resources.0.status.failed | default(0) > 0)

  retries: 6
  delay: 10

- name: Check that backup job {{ etcdbackupadfinis_namespace }}/etcd-backup-test succeeded
  ansible.builtin.assert:
    that: etcdbackupadfinis_job_result.resources.0.status.succeeded > 0
    fail_msg: The {{ etcdbackupadfinis_namespace }}/etcd-backup-test job failed
    quiet: true
