- import_tasks: keyval_create.yml
  vars:
    hvault_keyval_name: mykv
    hvault_keyval_reader:
      - role_name: default-reader
        sa_names: default
        sa_namespaces: '*'
      - role_name: external-secrets-operator
        sa_names: external-secrets
        sa_namespaces: external-secrets
      - role_name: vault-secrets-operator
        sa_names: vault-secrets-operator
        sa_namespaces: '*'
