- ansible.builtin.import_role:
    name: ansible-modules-hashivault

- ansible.builtin.import_tasks: install.yml

- ansible.builtin.import_tasks: initialize.yml
  when:
    - hvault_health_result.json.initialized | default(true) == false
    - hvault_unseal_secret_result.resources | length == 0

- ansible.builtin.import_tasks: unseal.yml

- ansible.builtin.import_tasks: admin_token.yml

- ansible.builtin.import_tasks: enable_audit.yml

- ansible.builtin.import_tasks: enable_kube_auth.yml

- ansible.builtin.import_tasks: enable_approle_auth.yml

- ansible.builtin.import_tasks: custom_keyval_create.yml
  when: hvault_custom_keyval_create

- ansible.builtin.import_tasks: custom_pki_create.yml
  when: hvault_custom_pki_create

- ansible.builtin.import_tasks: report_success.yml
