- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: get_infrastructure.yml

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/instance
    autogitops_app_dst_path: hashicorp-vault/instance
    autogitops_app_namespace: '{{ hvault_namespace }}'

- name: Obtain vault route
  ansible.builtin.import_tasks: connection_addr.yml

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for HashiCorp Vault to come up
  ansible.builtin.uri:
    url: '{{ hvault_addr }}/v1/sys/health'
    method: GET
    validate_certs: '{{ not hvault_skip_verify }}'
    status_code: [ 200, 501, 503 ]
  register: hvault_health_result
  until: >-
    hvault_health_result.status == 200 or
    hvault_health_result.json.sealed | default(false) or
    hvault_health_result.json.initialized | default(true) == false
  retries: 60
  delay: 10

- name: Retrieve the unseal secret if it exists
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: '{{ hvault_name }}-unseal-key'
    namespace: '{{ hvault_namespace }}'
  register: hvault_unseal_secret_result
