- name: Configure MicroShift
  ansible.builtin.template:
    src: config.yaml
    dest: /etc/microshift/config.yaml
    mode: '0644'
  notify:
    - Restart microshift
  become: true

- name: Start microshift service
  ansible.builtin.service:
    name: microshift
    state: started
    enabled: true
  become: true
