- name: Ensure certificate directory exists
  ansible.builtin.file:
    path: '{{ outer_item.dir }}'
    state: directory
    mode: '0755'
  become: true

- name: Install leaf certificate
  ansible.builtin.copy:
    content: '{{ item.content }}'
    dest: '{{ outer_item.dir }}/{{ item.name }}'
    mode: '0600'
  notify:
    - Restart microshift
  loop: '{{ outer_item.files }}'
  loop_control:
    label: '{{ outer_item.dir }}/{{ item.name }}'
  become: true
