- ansible.builtin.import_tasks: install_packages.yml

- ansible.builtin.import_tasks: configure_certificates.yml

- ansible.builtin.import_tasks: configure_crio.yml

- ansible.builtin.import_tasks: configure_storage.yml

- ansible.builtin.import_tasks: configure_microshift.yml

- ansible.builtin.import_tasks: report_success.yml
