- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: v1
        kind: Namespace
        name: hosted-clusters

- ansible.builtin.import_tasks: hypershift_aws_delete.yml

- ansible.builtin.import_tasks: cluster_discovery_delete.yml

- ansible.builtin.import_tasks: assisted_installer_delete.yml

- ansible.builtin.import_tasks: manifestwork_delete.yml
