- name: Deploy test-hello-work manifestwork
  kubernetes.core.k8s:
    template: manifestwork/test-hello-work-manifestwork.yaml

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for test-hello-work deployment to complete
  kubernetes.core.k8s_info:
    api_version: work.open-cluster-management.io/v1
    kind: ManifestWork
    namespace: local-cluster
    name: test-hello-work
    wait: true
    wait_condition:
      type: Available
    wait_sleep: 5
    wait_timeout: 800

- ansible.builtin.assert:
    that: query('kubernetes.core.k8s', api_version='v1', kind='ConfigMap', namespace='default', resource_name='test-hello-work') | length == 1
    fail_msg: ConfigMap default/test-hello-work can't be found.
    quiet: true
