- name: Create namespace {{ amqstreams_kafka_cluster_namespace }}
  kubernetes.core.k8s:
    template: kafka-cluster/namespace.yaml

- name: Deploy Kafka cluster
  kubernetes.core.k8s:
    definition: "{{ lookup('url', item, split_lines=false) }}"
    namespace: '{{ amqstreams_kafka_cluster_namespace }}'
  loop:
    - '{{ amqstreams_examples }}/kafka/kafka-persistent.yaml'

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for Kafka cluster deployment to complete
  kubernetes.core.k8s_info:
    api_version: kafka.strimzi.io/v1beta2
    kind: Kafka
    namespace: '{{ amqstreams_kafka_cluster_namespace }}'
    name: my-cluster
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600

- import_tasks: create_topics.yml
  vars:
    amqstreams_topics_namespace: '{{ amqstreams_kafka_cluster_namespace }}'
    amqstreams_topics_replicas: 3

- import_tasks: kafdrop_deploy.yml
  vars:
    amqstreams_kafdrop_namespace: '{{ amqstreams_kafka_cluster_namespace }}'
