- name: Create namespace {{ amqstreams_kafka_mirror_maker_namespace }}
  kubernetes.core.k8s:
    template: kafka-mirror-maker/namespace.yaml

- name: Deploy two Kafka instances and Mirror Maker
  kubernetes.core.k8s:
    definition: "{{ lookup('url', item, split_lines=false) }}"
    namespace: '{{ amqstreams_kafka_mirror_maker_namespace }}'
  loop:
    - '{{ amqstreams_examples }}/mirror-maker/kafka-source.yaml'
    - '{{ amqstreams_examples }}/mirror-maker/kafka-target.yaml'
    - '{{ amqstreams_examples }}/mirror-maker/kafka-mirror-maker-2-sync-groups.yaml'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Kafka Source deployment to complete
  kubernetes.core.k8s_info:
    api_version: kafka.strimzi.io/v1beta2
    kind: Kafka
    namespace: '{{ amqstreams_kafka_mirror_maker_namespace }}'
    name: cluster-a
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Kafka Target deployment to complete
  kubernetes.core.k8s_info:
    api_version: kafka.strimzi.io/v1beta2
    kind: Kafka
    namespace: '{{ amqstreams_kafka_mirror_maker_namespace }}'
    name: cluster-b
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Mirror Maker deployment to complete
  kubernetes.core.k8s_info:
    api_version: kafka.strimzi.io/v1beta2
    kind: KafkaMirrorMaker2
    namespace: '{{ amqstreams_kafka_mirror_maker_namespace }}'
    name: my-mirror-maker-2
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600
