- name: Configure passwordless sudo
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: configure_passwordless_sudo.yml

- name: Configure common users
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: configure_common_users.yml

- name: Subscribe RHEL
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: subscribe_rhel.yml

- name: Install tools
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: install_tools.yml

- name: Upgrade all packages
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: upgrade_all_packages.yml
  vars:
    machine_base_update_all_packages: '{{ container_base_update_all_packages }}'
    machine_base_update_all_packages_reboot: '{{ container_base_update_all_packages_reboot }}'
