- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: machine_base
      tags: machine_base

    - ansible.builtin.import_role:
        name: machine_microshift
      tags: machine_microshift
