- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: machine_base
      tags: machine_base

    - ansible.builtin.import_role:
        name: common_tasks
        tasks_from: configure_common_users.yml

    - ansible.builtin.import_role:
        name: machine_devel
        tasks_from: system_setup.yml
      when: ansible_facts.distribution == "Fedora"
      tags: machine_devel

    # Switch to user devel
    - ansible.builtin.set_fact:
        ansible_user: devel
      tags: machine_devel

- hosts: all
  tasks:
    - ansible.builtin.import_role:
        name: machine_devel
        tasks_from: user_setup.yml
      tags: machine_devel
