- hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.import_role:
        name: openshift_odf
        tasks_from: external_instance_delete.yml
      tags: odf_instance

    - ansible.builtin.import_role:
        name: openshift_odf
        tasks_from: operator_delete.yml
      tags: odf_operator
