- hosts: rhvh.lab.example.com
  tasks:
    - ansible.builtin.import_role:
        name: machine_base
      tags: machine_base

    - ansible.builtin.import_role:
        name: rhv_lab
      tags: rhv_lab
