- name: Retrieve cryostat instance
  kubernetes.core.k8s_info:
    api_version: operator.cryostat.io/v1beta1
    kind: Cryostat
    name: '{{ cryostat_instance_name }}'
    namespace: '{{ cryostat_instance_namespace }}'
    wait: true
    wait_condition:
      type: MainDeploymentAvailable
    wait_sleep: 10
    wait_timeout: 600
  register: cryostat_instance

- name: Set msg
  ansible.builtin.set_fact:
    msg: |
      Cryostat installed successfully.

      You can browse to:
      {{ cryostat_instance.resources.0.status.applicationUrl }}

      To display Grafana credentials type:
      oc extract --namespace {{ cryostat_instance_namespace }} secret/cryostat-grafana-basic --to -

      To display Cryostat JMX credentials type:
      oc extract --namespace {{ cryostat_instance_namespace }} secret/cryostat-jmx-auth --to -

- ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
