apiVersion: v1
kind: Secret
metadata:
  annotations:
    # Create the sa token secret after the service account was created or the
    # secret gets deleted
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: aap-mgmt
  name: aap-mgmt-sa-token-static
  namespace: kube-system
type: kubernetes.io/service-account-token
