- import_tasks: connection.yml

- assert:
    that: redhat_subscription_username | length > 0
    fail_msg: Variable 'redhat_subscription_username' must not be empty
    quiet: true

- assert:
    that: redhat_subscription_password | length > 0
    fail_msg: Variable 'redhat_subscription_password' must not be empty
    quiet: true

- name: Get Ansible Automation Platform subscriptions
  ansible.controller.subscriptions:
    username: '{{ redhat_subscription_username }}'
    password: '{{ redhat_subscription_password }}'
    filters: '{{ aap_subscription_filter }}'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
  register: aap_subscriptions_result

- assert:
    that: aap_subscriptions_result.subscriptions | length > 0
    fail_msg: No subscription for Ansible Automation Platform available.
    quiet: true

- name: Install controller license
  ansible.controller.license:
    subscription_id: '{{ aap_subscriptions_result.subscriptions.0.subscription_id }}'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/cluster-import
    autogitops_app_dst_path: aap/cluster-import
    autogitops_app_namespace: kube-system

- name: Grab service account token secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: aap-mgmt-sa-token-static
    namespace: kube-system
  register: aap_init_sa_secret_result

- import_role:
    name: openshift_common
    tasks_from: get_infrastructure.yml

- debug:
    var: aap_init_sa_secret_result.resources.0.data.token | b64decode

- name: Create OpenShift credential in Ansible Automation Platform
  ansible.controller.credential:
    name: '{{ oscommon_cluster_domain }}'
    credential_type: OpenShift or Kubernetes API Bearer Token
    organization: Default
    inputs:
      host: '{{ oscommon_cluster_url }}'
      bearer_token: '{{ aap_init_sa_secret_result.resources.0.data.token | b64decode }}'
      verify_ssl: true
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create cluster inventory
  ansible.controller.inventory:
    name: '{{ oscommon_cluster_domain }}'
    description: OpenShift cluster {{ oscommon_cluster_domain }}
    organization: Default
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create host
  ansible.controller.host:
    name: '{{ oscommon_cluster_domain }}'
    inventory: '{{ oscommon_cluster_domain }}'
    variables:
      ansible_connection: local
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create group OpenShift clusters
  ansible.controller.group:
    name: openshift_clusters
    description: OpenShift clusters
    inventory: '{{ oscommon_cluster_domain }}'
    hosts:
      - '{{ oscommon_cluster_domain }}'
    preserve_existing_hosts: true
    preserve_existing_children: true
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Add custom execution environment
  ansible.controller.execution_environment:
    name: Custom execution environment
    organization: Default
    image: quay.io/noseka1/ansible-base-ee:latest
    pull: always
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Add project Wait for Stable Cluster {{ oscommon_cluster_domain }}
  ansible.controller.project:
    name: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    description: Wait for cluster operators to stabilize
    organization: Default
    scm_update_on_launch: true
    scm_update_cache_timeout: 60
    scm_type: git
    scm_url: https://github.com/noseka1/ansible-base
    default_environment: Custom execution environment
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create job template
  ansible.controller.job_template:
    name: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    job_type: run
    organization: Default
    inventory: '{{ oscommon_cluster_domain }}'
    project: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    playbook: openshift_wait_for_stable_cluster.yml
    credentials:
      - '{{ oscommon_cluster_domain }}'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Launch a job
  ansible.controller.job_launch:
    job_template: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
  register: aap_init_job_result

# This Ansible task fails if the job failed
- name: Wait for job
  ansible.controller.job_wait:
    job_id: '{{ aap_init_job_result.id }}'
    timeout: 1200
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
