- assert:
    that: >-
      query('kubernetes.core.k8s', api_version='v1', kind='Service', resource_name='datadog-vector-instance',
        namespace=ddvector_namespace) | length == 1
    fail_msg: |
      Datadog Vector service doesn't exist. Is Datadog Vector installed on the cluster?
      Use the openshift_ddvector_deploy.yml playbook to install a Datadog Vector instance.
    quiet: true
  when: ddvector_check_connection

- set_fact:
    ddvector_hostname: 'datadog-vector-instance.{{ ddvector_namespace }}.svc'
    ddvector_port_syslog_udp: 1514
    ddvector_port_syslog_tcp: 9000
