- name: Obtain Datadog Vector service
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: datadog-vector-instance
    namespace: '{{ ddvector_namespace }}'
  register: ddvector_service_result

- ansible.builtin.assert:
    that: ddvector_service_result.resources | length == 1
    fail_msg: |
      Datadog Vector service doesn't exist. Is Datadog Vector installed on the cluster?
      Use the openshift_ddvector_deploy.yml playbook to install a Datadog Vector instance.
    quiet: true

- ansible.builtin.set_fact:
    ddvector_hostname: 'datadog-vector-instance.{{ ddvector_namespace }}.svc'
    ddvector_ip: '{{ ddvector_service_result.resources.0.spec.clusterIP }}'
    ddvector_port_syslog_udp: 1514
    ddvector_port_syslog_tcp: 9000
    ddvector_port_socket_udp: 1520
