---
version: 3
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
images:
  base_image:
    name: registry.fedoraproject.org/fedora:43
additional_build_steps:
  prepend_base: |
    RUN dnf install -y \
      git \
      python3 \
      pip3
    # Install oc and kubectl
    RUN curl --location --no-progress-meter \
      https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | \
      tar xvfz - --directory /usr/local/bin oc kubectl && \
      kubectl completion bash > /etc/bash_completion.d/kubectl && \
      oc completion bash > /etc/bash_completion.d/oc
