- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for {{ wait_for_deployment_namespace }}/{{ wait_for_deployment_name }} deployment to complete
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: '{{ wait_for_deployment_name }}'
    namespace: '{{ wait_for_deployment_namespace }}'
    wait: true
    wait_condition:
      type: Available
    wait_sleep: 10
    wait_timeout: '{{ (wait_for_deployment_retries | default(60)) * 10 }}'
