- name: Increment retry count
  ansible.builtin.set_fact:
    stable_cluster_retry_count: '{{ (stable_cluster_retry_count | int) + 1 }}'

- ansible.builtin.fail:
    msg: Ended after {{ stable_cluster_retries }}
  when: (stable_cluster_retry_count | int ) > stable_cluster_retries

- name: Retrieve cluster status
  block:
    - name: Attempt to retrieve cluster status
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: ClusterOperator
      register: clusteroperator_result

  rescue:
    - name: Handle failure
      ansible.builtin.debug:
        msg: "There was an error retrieving cluster status, please check. Continuing with automation..."
      changed_when: true

- name: Create unavailable, progressing, and degraded operator groups
  ansible.builtin.set_fact:
    clusteroperator_count: >-
      {{ clusteroperator_result.resources | default([]) | length }}
    clusteroperator_unavailable: >-
      {{ clusteroperator_result.resources | default([]) | json_query("[?status.conditions[?type=='Available' && status=='False']].metadata.name") }}
    clusteroperator_progressing: >-
      {{ clusteroperator_result.resources | default([]) | json_query("[?status.conditions[?type=='Progressing' && status=='True']].metadata.name") }}
    clusteroperator_degraded: >-
      {{ clusteroperator_result.resources | default([]) | json_query("[?status.conditions[?type=='Degraded' && status=='True']].metadata.name") }}

- name: Set job complete to true
  ansible.builtin.set_fact:
    stable_cluster_job_complete: true
  when:
    - clusteroperator_count | int > 0
    - clusteroperator_unavailable | length == 0
    - clusteroperator_progressing | length == 0
    - clusteroperator_degraded | length == 0

- name: |
    {{ stable_cluster_retries - (stable_cluster_retry_count | int) }} retries remaining.
    Cluster operator status:
      Count: {{ clusteroperator_count }}
      Unavailable: {{ clusteroperator_unavailable }}
      Progressing: {{ clusteroperator_progressing }}
      Degraded: {{ clusteroperator_degraded }}
    ''
    To skip waiting for the operators you can set Ansible variable stable_cluster_wait_for_operators = false.
    ''
  ansible.builtin.pause:
    seconds: 120
  when: not stable_cluster_job_complete

- ansible.builtin.include_tasks: wait_for_stable_cluster_subtasks.yml
  when: not stable_cluster_job_complete
