- name: Deploy Serverless operator
  kubernetes.core.k8s:
    definition: "{{ lookup('pipe', 'oc kustomize ' + serverless_kustomizations.operator) }}"

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    oscomm_subscription_name: '{{ serverless_subscription_name }}'
    oscomm_subscription_namespace: '{{ serverless_subscription_namespace }}'

- name: Deploy Knative Serving
  kubernetes.core.k8s:
    definition: "{{ lookup('pipe', 'oc kustomize ' + serverless_kustomizations.serving) }}"

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for Knative Serving deployment to complete
  kubernetes.core.k8s_info:
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeServing
    name: knative-serving
    namespace: knative-serving
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600

- name: Deploy Knative Eventing
  kubernetes.core.k8s:
    definition: "{{ lookup('pipe', 'oc kustomize ' + serverless_kustomizations.eventing) }}"

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for Knative Eventing deployment to complete
  kubernetes.core.k8s_info:
    api_version: operator.knative.dev/v1alpha1
    kind: KnativeEventing
    name: knative-eventing
    namespace: knative-eventing
    wait: true
    wait_condition:
      type: Ready
    wait_sleep: 10
    wait_timeout: 600
