- ansible.builtin.import_tasks: hub_deploy_subtasks.yml

- ansible.builtin.import_tasks: gitops_config.yml
  when: rhacm_instance_import_to_argocd

- ansible.builtin.import_tasks: users_config.yml

- ansible.builtin.import_role:
    name: openshift_multicluster_engine
    tasks_from: common_deploy.yml

- ansible.builtin.import_tasks: hub_report_success.yml
