- import_role:
    name: openshift_common
    tasks_from: install_plan_approve
  vars:
    oscomm_subscription_name: vault-secrets-operator
    oscomm_subscription_namespace: vault-secrets-operator
  tags: vso_operator

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/operator
    autogitops_app_dst_path: vault-secrets/operator
    autogitops_app_namespace: vault-secrets-operator
  tags: vso_operator

- import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    oscomm_subscription_name: vault-secrets-operator
    oscomm_subscription_namespace: vault-secrets-operator
  tags: vso_operator

- import_role:
    name: openshift_hashicorp_vault
    tasks_from: connection_addr.yml
  tags: vso_instance

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/instance
    autogitops_app_dst_path: vault-secrets/instance
    autogitops_app_namespace: vault-secrets-authconfig
  tags: vso_instance

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/example
    autogitops_app_dst_path: vault-secrets/example
    autogitops_app_namespace: vault-secrets-example
  tags: vso_example

- name: Retrieve the respective secret created by the operator
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: example
    namespace: vault-secrets-example
  register: vso_example_result
  tags: vso_example

- name: Fail if the secret value is not correct
  assert:
    that: (vso_example_result.resources.0.data.testkey | b64decode) == 'testvalue'
    fail_msg: The secret value is not 'testvalue'.
  tags: vso_example
