apiVersion: hive.openshift.io/v1
kind: ClusterImageSet
metadata:
  labels:
    channel: fast
    visible: "true"
  name: img{{ mceinfraenv_info.ocp_release_image | regex_replace('_', '-',) }}-appsub
spec:
  releaseImage: quay.io/openshift-release-dev/ocp-release:{{ mceinfraenv_info.ocp_release_image }}
