- name: Remove custom kernel arguments to OpenShift nodes (will cause nodes to restart)
  kubernetes.core.k8s:
    template: igb/65-network-sriov-igb-mc.yaml
    wait: true
    state: absent
  register: sriovnet_machineconfig_result
  loop:
    - worker
    - master

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_stable_cluster.yml
  vars:
    stable_cluster_delay: 120
    stable_cluster_retries: 10
  when: sriovnet_machineconfig_result is changed
