apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    alerts.k8s.io/KubePersistentVolumeFillingUp: disabled
  name: example-rootdisk-target
  namespace: kubevirt-migrate-source
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-hostpath
  volumeMode: Filesystem
