- name: Delete and recreate application directory {{ autogitops_app_dst_dir }}
  ansible.builtin.file:
    path: '{{ autogitops_app_dst_dir }}'
    state: '{{ item }}'
    mode: '0755'
  loop:
    - absent
    - directory

- name: Create a .gitkeep file to allow checking the empty directory into git
  ansible.builtin.copy:
    dest: '{{ autogitops_app_dst_dir }}/.gitkeep'
    content: ''
    mode: '0644'
