- name: Set application variables
  ansible.builtin.set_fact:
    autogitops_app_name: '{{ autogitops_app_dst_path | regex_replace("/", "-") }}'
    autogitops_app_project: '{{ oscommon_cluster_domain | regex_replace("\.", "-") }}'
    autogitops_argocd_namespace: ag-{{ oscommon_cluster_domain | regex_replace('\.', '-') }}

- ansible.builtin.import_tasks: local_repo_create.yml

- name: Set application destination directory
  ansible.builtin.set_fact:
    autogitops_app_dst_dir: '{{ autogitops_git_dir }}/{{ autogitops_app_dst_path }}'

- name: Ensure root application destination directory exists
  ansible.builtin.file:
    path: '{{ autogitops_app_dst_dir }}'
    state: directory
    mode: '0755'

- name: Create a .gitkeep file to allow checking the empty directory into git
  ansible.builtin.copy:
    dest: '{{ autogitops_app_dst_dir }}/.gitkeep'
    content: ''
    mode: '0644'

- ansible.builtin.import_tasks: local_repo_push.yml

- name: Create cluster namespace and root application
  kubernetes.core.k8s:
    template:
      - namespace.yaml
      - application.yaml
