- import_role:
    name: openshift_hashicorp_vault
    tasks_from: keyval_create.yml
  vars:
    hvault_keyval_name: ansible
    hvault_keyval_approle:
      - ansible

- import_role:
    name: openshift_hashicorp_vault
    tasks_from: connection_approle.yml
  vars:
    hvault_approle_name: ansible

- name: Create Custom HashiCorp Vault credential type
  ansible.controller.credential_type:
    name: Custom HashiCorp Vault
    description: Authetication to HashiCorp Vault using approle
    kind: cloud
    inputs: '{{ lookup("file", "hashicorp_vault/inputs.yml") | from_yaml }}'
    injectors: '{{ lookup("file", "hashicorp_vault/injectors.yml") | from_yaml }}'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create HashiCorp Vault credential in Ansible Automation Platform
  ansible.controller.credential:
    name: '{{ oscommon_cluster_domain }} HashiCorp Vault'
    credential_type: Custom HashiCorp Vault
    organization: Default
    inputs:
      vault_addr: '{{ hvault_addr }}'
      vault_cacert: '{{ aap_trusted_ca_certificate }}'
      vault_skip_verify: false
      vault_approle_role_id: '{{ hvault_approle_role_id }}'
      vault_approle_secret_id: '{{ hvault_approle_secret }}'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
