- ansible.builtin.import_tasks: connection.yml

- ansible.builtin.import_tasks: init/license.yml

- ansible.builtin.import_tasks: init/openshift.yml

- ansible.builtin.import_tasks: init/hashicorp_vault.yml

- ansible.builtin.import_tasks: init/job.yml
