- name: Create cluster inventory
  ansible.controller.inventory:
    name: '{{ oscommon_cluster_domain }}'
    description: OpenShift cluster {{ oscommon_cluster_domain }}
    organization: Default
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create host
  ansible.controller.host:
    name: '{{ oscommon_cluster_domain }}'
    inventory: '{{ oscommon_cluster_domain }}'
    variables:
      ansible_connection: local
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create group OpenShift clusters
  ansible.controller.group:
    name: openshift_clusters
    description: OpenShift clusters
    inventory: '{{ oscommon_cluster_domain }}'
    hosts:
      - '{{ oscommon_cluster_domain }}'
    preserve_existing_hosts: true
    preserve_existing_children: true
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Add custom execution environment
  ansible.controller.execution_environment:
    name: Custom execution environment
    organization: Default
    image: quay.io/noseka1/ansible-base-ee:latest
    pull: always
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Add project Wait for Stable Cluster {{ oscommon_cluster_domain }}
  ansible.controller.project:
    name: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    description: Wait for cluster operators to stabilize
    organization: Default
    scm_update_on_launch: true
    scm_update_cache_timeout: 60
    scm_type: git
    scm_url: https://github.com/noseka1/ansible-base
    default_environment: Custom execution environment
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Create job template
  ansible.controller.job_template:
    name: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    job_type: run
    organization: Default
    inventory: '{{ oscommon_cluster_domain }}'
    project: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    playbook: openshift_wait_for_stable_cluster.yml
    credentials:
      - '{{ oscommon_cluster_domain }} Kubernetes API'
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'

- name: Launch a job
  ansible.controller.job_launch:
    job_template: Wait for Stable Cluster {{ oscommon_cluster_domain }}
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
  register: aap_init_job_result

# This Ansible task fails if the job failed
- name: Wait for job
  ansible.controller.job_wait:
    job_id: '{{ aap_init_job_result.id }}'
    timeout: 1200
    controller_host: '{{ aap_connection_host }}'
    controller_username: '{{ aap_connection_username }}'
    controller_password: '{{ aap_connection_password }}'
