- import_role:
    name: openshift_common
    tasks_from: wait_for_stable_cluster.yml
  vars:
    stable_cluster_delay: 0
    stable_cluster_retries: 10

- import_role:
    name: ansible-modules-hashivault

- name: Retrieve secret from HashiCorp vault
  hashivault_read:
    mount_point: ansible
    secret: testsecret
    key: testkey
    version: 2
  register: aap_test_hashivault_read_result
