# This is a dummy cloud-init secret. During migration, content of this
# cloud-init volume will be overwritten by the content from the source VM.
apiVersion: v1
kind: Secret
metadata:
  name: example-cloudinit
  namespace: kubevirt-migrate-target
stringData:
  userdata: |
    #cloud-config
