apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    # Specifies the runStrategy after migration, which should be the same as
    # the source, in this case it is Always.
    kubevirt.io/restore-run-strategy: Always
  name: example
  namespace: kubevirt-migrate-target
spec:
  # The runStrategy must be set to WaitAsReceiver, signaling to KubeVirt that
  # this is a special target virtual machine and that standard virtual machine
  # commands (start/stop) will not function until the migration is completed.
  runStrategy: WaitAsReceiver
  template:
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootdisk
          interfaces:
          - macAddress: 02:65:34:bb:53:bb
            masquerade: {}
            model: virtio
            name: default
          logSerialConsole: true
          rng: {}
        firmware:
          serial: 72092eac-2b37-4384-b896-4ff0e18b9e02
          uuid: cd11f840-8ab2-42a1-909f-cbe0851647d4
        memory:
          guest: 2Gi
      evictionStrategy: LiveMigrate
      networks:
      - name: default
        pod: {}
      volumes:
      - cloudInitNoCloud:
          secretRef:
            name: example-cloudinit
        name: cloudinitdisk
      - persistentVolumeClaim:
          claimName: example-rootdisk
        name: rootdisk
