apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example
  namespace: vault-secrets-example
spec:
  vaultAuthRef: vault-secrets-authconfig/vault-auth
  mount: mykv
  type: kv-v2
  path: testsecret
  refreshAfter: 60s
  destination:
    create: true
    name: example
