apiVersion: v1
kind: Secret
metadata:
  name: example-cloudinit
  namespace: kubevirt-migrate-source
stringData:
  userdata: |
    #cloud-config
    user: admin
    password: password
    chpasswd:
      expire: false
    ssh_pwauth: true
    ssh_authorized_keys: []
