- name: Create cluster configuration directory {{ osclusterinstall_info.config_dir }}
  ansible.builtin.file:
    path: '{{ osclusterinstall_info.config_dir }}'
    state: directory
    mode: '0755'

- name: Download openshift-install archive {{ osclusterinstall_installer_url }}
  ansible.builtin.get_url:
    url: '{{ osclusterinstall_installer_url }}'
    dest: '{{ osclusterinstall_info.config_dir }}/{{ osclusterinstall_installer_url | basename }}'
  retries: 3

- name: Extract openshift-install
  ansible.builtin.unarchive:
    src: '{{ osclusterinstall_info.config_dir }}/{{ osclusterinstall_installer_url | basename }}'
    dest: '{{ osclusterinstall_info.config_dir }}'
    exclude:
      - README.md

- name: Get installer info
  ansible.builtin.command: '{{ osclusterinstall_info.config_dir }}/openshift-install version'
  changed_when: false
  register: osclusterinstall_installer_version

- name: Show installer info
  ansible.builtin.debug:
    var: osclusterinstall_installer_version.stdout_lines
