- name: Retrieve ingress configuration
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
  register: osclusterpostinst_ingress_result

- name: Retrieve cluster nodes
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Node
  register: osclusterpostinst_nodes_result

- ansible.builtin.import_role:
    name: openshift_datadog_vector
    tasks_from: get_connection.yml
  when: osclusterpostinst_send_ingress_access_logs_to_syslog_enabled

- name: Configure default ingresscontroller
  kubernetes.core.k8s:
    template: default-ingresscontroller.yaml
