- import_role:
    name: openshift_datadog_vector
    tasks_from: get_connection.yml
  when: osclusterpostinst_send_network_audit_logs_to_syslog_enabled

- name: Enable multi-network policy
  kubernetes.core.k8s:
    template: network/cluster-network.yaml
