- ansible.builtin.set_fact:
    mcehostedcluster_info: '{{ mcehostedcluster_agent }}'
  tags: mcehostedcluster_instance

# Detach the cluster from MCE before deleting the cluster
- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: cluster.open-cluster-management.io/v1
        kind: ManagedCluster
        name: '{{ mcehostedcluster_info.cluster_name }}'
    delete_kubernetes_objects_retries: 60
  tags: mcehostedcluster_instance

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_delete.yml
  vars:
    autogitops_app_dst_path: mce/hosted-cluster/{{ mcehostedcluster_info.cluster_name }}/instance
  tags: mcehostedcluster_instance

- ansible.builtin.import_tasks: common/namespace_delete.yml
  tags: mcehostedcluster_instance

- ansible.builtin.import_role:
    name: openshift_multicluster_engine_infraenv
    tasks_from: delete.yml
  vars:
    mceinfraenv_info: '{{ mcehostedcluster_agent }}'
  tags: mcehostedcluster_infraenv
