- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for cluster deployment of {{ mcemanagedcluster_info.cluster_name }} to complete
  kubernetes.core.k8s_info:
    api_version: hive.openshift.io/v1
    kind: ClusterDeployment
    name: '{{ mcemanagedcluster_info.cluster_name }}'
    namespace: '{{ mcemanagedcluster_info.cluster_name }}'
    wait: true
    wait_condition:
      type: Provisioned
    wait_sleep: 5
    wait_timeout: 60
  register: mcemanagedcluster_clusterdeployment_result

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for {{ mcemanagedcluster_info.cluster_name }} to connect to Hub
  kubernetes.core.k8s_info:
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: '{{ mcemanagedcluster_info.cluster_name }}'
    wait: true
    wait_condition:
      type: ManagedClusterConditionAvailable
    wait_sleep: 10
    wait_timeout: 300

- name: Set msg
  set_fact:
    msg: |-
      Cluster {{ mcemanagedcluster_info.cluster_name }} deployed successfully.
      You can download the admin kubeconfig by issuing 'oc extract -n {{ mcemanagedcluster_info.cluster_name }} secret/{{ mcemanagedcluster_clusterdeployment_result.resources.0.spec.clusterMetadata.adminKubeconfigSecretRef.name }} --keys kubeconfig'

- debug:
    msg: "{{ msg.split('\n') }}"
