apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-vector-instance
  namespace: {{ ddvector_manage_namespace }}
  labels:
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: datadog-vector-instance
    app.kubernetes.io/component: Stateless-Aggregator
automountServiceAccountToken: true
