- import_role:
    name: openshift_common
    tasks_from: install_plan_approve
  vars:
    oscomm_subscription_name: ingress-node-firewall
    oscomm_subscription_namespace: openshift-ingress-node-firewall

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/operator
    autogitops_app_dst_path: ingress-node-firewall/operator
    autogitops_app_namespace: openshift-ingress-node-firewall

- import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    oscomm_subscription_name: ingress-node-firewall
    oscomm_subscription_namespace: openshift-ingress-node-firewall

- import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/instance
    autogitops_app_dst_path: ingress-node-firewall/instance
    autogitops_app_namespace: openshift-ingress-node-firewall

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for ingress node firewall daemonset to deploy
  kubernetes.core.k8s_info:
    api_version: ingressnodefirewall.openshift.io/v1alpha1
    kind: IngressNodeFirewallConfig
    name: ingressnodefirewallconfig
    namespace: openshift-ingress-node-firewall
    wait: true
    wait_condition:
      type: Available
    wait_sleep: 10
    wait_timeout: 600
