env:
  VAULT_ADDR: '{{ vault_addr }}'
  VAULT_SKIP_VERIFY: '{{ vault_skip_verify | default(false) }}'
  VAULT_APPROLE_ROLE_ID: '{{ vault_approle_role_id }}'
  VAULT_APPROLE_SECRET_ID: '{{ vault_approle_secret_id }}'
