- name: Make sure target channel is defined
  ansible.builtin.assert:
    that: openshift_cluster_upgrade_target_channel | default('') | length > 0
    fail_msg: 'Upgrade target channel is not defined. Example: stable-4.20'
    quiet: true

- name: Make sure target version is defined
  ansible.builtin.assert:
    that: openshift_cluster_upgrade_target_version | default('') | length > 0
    fail_msg: 'Upgrade target version is not defined. Examples: 4.20.0, latest'
    quiet: true

- name: Retrieve and set target version (for latest)
  when: openshift_cluster_upgrade_target_version == 'latest'
  block:
    - name: Retrieve latest version on channel {{ openshift_cluster_upgrade_target_channel }}
      ansible.builtin.script: files/openshift_upgrade_path.py {{ openshift_cluster_upgrade_target_channel }}
      changed_when: false
      register: openshift_cluster_upgrade_latest_version

    - name: Set target OpenShift version (resolved)
      ansible.builtin.set_fact:
        openshift_cluster_upgrade_target_version_resolved: '{{ openshift_cluster_upgrade_latest_version.stdout_lines[0] }}'

- name: Set target OpenShift version (direct)
  when: openshift_cluster_upgrade_target_version != 'latest'
  ansible.builtin.set_fact:
    openshift_cluster_upgrade_target_version_resolved: '{{ openshift_cluster_upgrade_target_version }}'

- name: Show upgrade start message
  ansible.builtin.debug:
    msg: Upgrading OpenShift to version {{ openshift_cluster_upgrade_target_version_resolved }}
