- ansible.builtin.import_tasks: compute_target_version.yml

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_stable_cluster.yml
  vars:
    stable_cluster_delay: 0
    stable_cluster_retries: 60

- name: Retrieve current cluster version
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result

- ansible.builtin.set_fact:
    ocu_current_version: >-
      {{ ocu_clusterversion_result | json_query('resources[0].status.history[?state==`Completed`].version | [0]') }}

- ansible.builtin.debug:
    msg: Current cluster version is {{ ocu_current_version }}

- name: Compute upgrade path {{ ocu_current_version }} -> {{ ocu_target_version_resolved }}
  ansible.builtin.script: |-
    files/openshift_upgrade_path.py \
      {{ ocu_current_version }} \
      {{ ocu_target_channel }} \
      {{ ocu_target_version_resolved }}
  changed_when: false
  register: ocu_upgrade_path

- ansible.builtin.debug:
    var: ocu_upgrade_path.stdout | from_json

- name: Provide administrator acknowledgment to upgrade
  kubernetes.core.k8s:
    template: admin-acks-cm.yaml

- name: Perform OpenShift cluster upgrade(s)
  ansible.builtin.include_tasks: upgrade.yml
  loop: '{{ ocu_upgrade_path.stdout | from_json }}'

- name: Retrieve the upgrade history
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result

- name: Show upgrade history
  ansible.builtin.debug:
    var: ocu_clusterversion_result.resources.0.status.history
