- name: Switch channel to {{ item.channel }}
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: '{{ item.channel }}'

- name: Waiting for the target version to become available since {{ lookup("pipe", "date +%r") }}
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result
  until:
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.availableUpdates is defined
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.availableUpdates | selectattr('version', 'equalto', item.version) | list | length > 0
  retries: 60
  delay: 10

- name: Trigger upgrade to version {{ item.version }}
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        desiredUpdate:
          version: '{{ item.version }}'

- name: Waiting for the upgrade to start since {{ lookup("pipe", "date +%r") }}
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: openshift_cluster_upgrade_clusterversion_result
  until:
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions is defined
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Progressing') | list | length > 0
    - (openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Progressing') | first).status == "True"
  retries: 300
  delay: 1

- name: Waiting for the upgrade to complete since {{ lookup("pipe", "date +%r") }}
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: openshift_cluster_upgrade_clusterversion_result
  until:
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions is defined
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Progressing') | list | length > 0
    - (openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Progressing') | first).status == "False"
    - openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | list | length > 0
    - (openshift_cluster_upgrade_clusterversion_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | first).status == "True"
  retries: 360
  delay: 20

- name: Wait for stable cluster
  ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_stable_cluster.yml
  vars:
    stable_cluster_delay: 0
    stable_cluster_retries: 60
