- name: Switch channel to {{ item.channel }}
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        channel: '{{ item.channel }}'

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for the {{ item.version }} target version to become available
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result
  until:
    - ocu_clusterversion_result.resources.0.status.availableUpdates | default([]) |
        selectattr('version', 'equalto', item.version) | length > 0
  retries: 60
  delay: 10

- name: Trigger upgrade to version {{ item.version }}
  kubernetes.core.k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      metadata:
        name: version
      spec:
        desiredUpdate:
          version: '{{ item.version }}'

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for the upgrade to start
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result
  until:
    - (ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Progressing`].status | [0]') == 'True')
      or
      (ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Upgradeable`].status | [0]') == 'False')
  retries: 120
  delay: 1

- ansible.builtin.fail:
    msg: |
      Cluster not upgradeable.
       Reason: {{ ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Upgradeable`].reason | [0]') }}
      Message: {{ ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Upgradeable`].message | [0]') }}
  when:
    - (ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Upgradeable`].status | [0]') == 'False')

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for the upgrade to version {{ item.version }} to complete
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: ClusterVersion
    name: version
  register: ocu_clusterversion_result
  until:
    - ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Progressing`].status | [0]') == 'False'
    - ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Failing`].status | [0]') == 'False'
    - ocu_clusterversion_result | json_query('resources[0].status.conditions[?type==`Available`].status | [0]') == 'True'
    - ocu_clusterversion_result.resources.0.status.history | selectattr('version', 'equalto', item.version) |
        map(attribute='state') | first | default('') == 'Completed'
  retries: 360
  delay: 20

- ansible.builtin.import_role:
    name: openshift_common
    tasks_from: wait_for_stable_cluster.yml
  vars:
    stable_cluster_delay: 0
    stable_cluster_retries: 60
