- ansible.builtin.import_tasks: operator_deploy.yml
  tags: rook_ceph_operator

- ansible.builtin.import_tasks: instance_deploy.yml
  tags: rook_ceph_instance

- ansible.builtin.import_tasks: report_success.yml
  tags: rook_ceph_instance
