- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart crio
  ansible.builtin.service:
    name: crio
    state: restarted
  become: true

- name: Restart create-odf-lvm
  ansible.builtin.service:
    name: create-odf-lvm
    state: restarted
  become: true

- name: Restart microshift
  ansible.builtin.service:
    name: microshift
    state: restarted
  become: true
