- name: Install rpms
  ansible.builtin.yum:
    name:
      - nfs-utils
    state: present
  become: true

- name: Start NFS server services
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - nfs-server
    - rpcbind
  become: true

- name: Create group kvm
  ansible.builtin.group:
    name: kvm
    gid: 36
  become: true

- name: Create user vdsm
  ansible.builtin.user:
    name: vdsm
    uid: 36
    groups:
      - kvm
  become: true

- name: Create /storage directory
  ansible.builtin.file:
    path: /storage
    owner: vdsm
    group: kvm
    state: directory
    mode: '0755'
  become: true

- name: Export /storage via NFS
  ansible.builtin.template:
    src: exports
    dest: /etc/exports
    mode: '0644'
  register: nfs_config

- name: Restart NFS services
  ansible.builtin.service:
    name: '{{ item }}'
    state: restarted
  loop:
    - nfs-server
    - rpcbind
  when: nfs_config is changed
  become: true
