- name: Enable RHV repos
  ansible.builtin.import_tasks: enable_rhv_repos.yml

- name: Install NFS storage
  ansible.builtin.import_tasks: install_nfs.yml

- name: Deploy oVirt engine appliance
  ansible.builtin.import_tasks: deploy_engine.yml
