- name: Install containerd
  ansible.builtin.yum:
    name: containerd.io
  become: true

- name: Generate default configuration
  ansible.builtin.command: containerd config default
  changed_when: false
  register: containerd_config

- name: Set containerd_config
  ansible.builtin.set_fact:
    containerd_config: '{{ containerd_config.stdout | regex_replace("SystemdCgroup = false", "SystemdCgroup = true") }}'

- name: Create containerd configuration file
  ansible.builtin.copy:
    content: '{{ containerd_config }}'
    dest: /etc/containerd/config.toml
    mode: '0644'
  notify: Restart containerd
  become: true

- name: Start containerd service
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
  become: true
