- name: Create configuration for openshift-install
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: '0644'
  loop:
    - { src: '{{ osclusterinstall_platform | lower }}/install-config.yaml', dest: '{{ osclusterinstall_info.config_dir }}/install-config.yaml' }
    - { src: '{{ osclusterinstall_platform | lower }}/install-config.yaml', dest: '{{ osclusterinstall_info.config_dir }}/install-config.backup.yaml' }
  no_log: true

- debug:
    msg: You can follow the installation logs using 'tail -f {{ osclusterinstall_info.config_dir }}/.openshift_install.log'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the installation to complete
  command: >-
    ./openshift-install create cluster --dir . --log-level debug
  args:
    chdir: '{{ osclusterinstall_info.config_dir }}'
