- name: Check the install_complete timestamp
  stat:
    path: '{{ osclusterinstall_info.config_dir }}/install_complete'
    get_checksum: false
    get_mime: false
  register: osclusterinstall_install_complete_result

- when: osclusterinstall_install_complete_result.stat.exists
  block:
    - include_tasks: common/cluster_delete.yml
      when:
        - osclusterinstall_platform != 'AGENT'

    - include_tasks: agent/cluster_delete.yml
      when:
        - osclusterinstall_platform == 'AGENT'
