- name: Check the install_complete timestamp
  stat:
    path: '{{ osclusterinstall_info.config_dir }}/install_complete'
    get_checksum: false
    get_mime: false
  register: osclusterinstall_install_complete_result

- debug:
    msg: >-
      Found cluster installation timestamp in directory {{ osclusterinstall_info.config_dir }}, assuming that the
      cluster already exists, skipping the installation. If you are trying to reinstall the cluster, delete the cluster
      using an Ansible playbook before running this playbook.
  when:
    - osclusterinstall_install_complete_result.stat.exists

- when: not osclusterinstall_install_complete_result.stat.exists
  block:
    - name: Set target OpenShift version
      set_fact:
        osclusterinstall_version_resolved: '{{ osclusterinstall_info.version }}'
      when:
        - osclusterinstall_info.version != 'latest'

    - import_tasks: common/cluster_version.yml
      when:
        - osclusterinstall_info.version == 'latest'

    - import_tasks: common/cluster_installer.yml

    - include_tasks: common/cluster_install.yml
      when:
        - osclusterinstall_platform != 'AGENT'

    - include_tasks: agent/cluster_install.yml
      when:
        - osclusterinstall_platform == 'AGENT'

    - name: Create the timestamp
      file:
        path: '{{ osclusterinstall_info.config_dir }}/install_complete'
        state: touch
        mode: '0644'

- import_tasks: common/report_success.yml

- import_role:
    name: openshift_cluster_postinstall
    tasks_from: deploy.yml
  environment:
    K8S_AUTH_KUBECONFIG: '{{ osclusterinstall_info.config_dir }}/auth/kubeconfig'
    KUBECONFIG: '{{ osclusterinstall_info.config_dir }}/auth/kubeconfig'
  when: osclusterinstall_run_postinstall
