mcehostedcluster_kubevirt:
  cluster_name: mycluster20
  ocp_release_image: 4.21.3-x86_64
  control_plane_replicas: 1
  data_plane_replicas: 2
  etcd_storageclass: ''
  ssh_authorized_key: ''
  clusterwide_proxy: {}
  trusted_ca_bundle: ''
  nodepool_rootvolume_accessmodes:
    - ReadWriteOnce
  nodepool_compute_cores: 2
  nodepool_compute_memory: 6Gi
  nodepool_rootvolume_size: 32Gi
  nodepool_rootvolume_storageclass: ''
  # Allowed volume mode values are Filesystem or Block
  nodepool_rootvolume_volumemode: Filesystem

mcehostedcluster_baremetal:
  cluster_name: mycluster21
  ocp_release_image: 4.21.3-x86_64
  control_plane_replicas: 1
  data_plane_replicas: 2
  etcd_storageclass: ''
  ssh_authorized_key: ''
  clusterwide_proxy: {}
  trusted_ca_bundle: ''
  dns_base_domain: example.com
  # Network type options are 'static' or 'dhcp'
  network_type: dhcp
  location: myregion
  cpu_architecture: x86_64
  cluster_nodes_shared:
    bmh:
      bmc:
        username: dummy
        password: dummy
        disable_certificate_verification: true
      # Choose boot mode 'legacy' or 'UEFI'
      boot_mode: legacy
  cluster_nodes_individual:
    master1:
      role: master
      # Optionally, boot the node using BMC:
      bmh:
        bmc:
          address: redfish-virtualmedia+https://sushy.lab.example.com:8000/redfish/v1/Systems/00000000-0000-0008-0021-000000000000
        boot_macaddr: '52:54:00:08:21:00'
        root_device_hints:
          deviceName: /dev/vda
    master2:
      role: master
      bmh:
        bmc:
          address: redfish-virtualmedia+https://sushy.lab.example.com:8000/redfish/v1/Systems/00000000-0000-0008-0022-000000000000
        boot_macaddr: '52:54:00:08:22:00'
        root_device_hints:
          deviceName: /dev/vda
    master3:
      role: master
      bmh:
        bmc:
          address: redfish-virtualmedia+https://sushy.lab.example.com:8000/redfish/v1/Systems/00000000-0000-0008-0023-000000000000
        boot_macaddr: '52:54:00:08:23:00'
        root_device_hints:
          deviceName: /dev/vda
