- name: Load required kernel modules
  community.general.modprobe:
    name: '{{ item }}'
  loop:
    - br_netfilter
    - overlay
    - ip_tables
  become: true

- name: Setup required sysctl params
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    reload: true
  loop:
    - { key: net.bridge.bridge-nf-call-iptables,  value: 1 }
    - { key: net.bridge.bridge-nf-call-ip6tables, value: 1 }
    - { key: net.ipv4.ip_forward,                 value: 1 }
  become: true

- name: Put SELinux in permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive
  become: true

- name: Add Kubernetes Yum repository
  ansible.builtin.copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0644'
  become: true

- name: Install Kubernetes bootstrap packages
  ansible.builtin.yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    disable_excludes: kubernetes
  become: true

- name: Ensure the kubelet services is enabled and started
  ansible.builtin.service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
    - kubelet
  become: true

- name: Create a kubeadm config directory
  ansible.builtin.file:
    dest: '{{ kubeadm_config_dir }}'
    state: directory
    mode: '0755'

- name: Install further required packages
  ansible.builtin.yum:
    name: iproute-tc
  become: true

- name: Verify that container runtime socket {{ kubeadm_config_crisocket }} is functional
  ansible.builtin.command: crictl --runtime-endpoint unix://{{ kubeadm_config_crisocket }}
  changed_when: false
  become: true
