- name: Copy over the kubeadm master configuration
  ansible.builtin.template:
    src: kubeadm_master_config.yml
    dest: '{{ kubeadm_config_dir }}'
    mode: '0644'

- name: Create Kubernetes certificate directory
  ansible.builtin.file:
    path: '{{ kubeadm_config.cert_dir }}'
    state: directory
    mode: '0755'
  become: true

- name: Copy over the custom CA certificate and key
  ansible.builtin.copy:
    content: '{{ item.content }}'
    dest: '{{ item.file }}'
    mode: '{{ item.mode }}'
  no_log: true
  loop:
    - { content: '{{ kubeadm_ca_cert.crt }}', file: '{{ kubeadm_config.cert_dir }}/ca.crt', mode: '0644' }
    - { content: '{{ kubeadm_ca_cert.key }}', file: '{{ kubeadm_config.cert_dir }}/ca.key', mode: '0640' }
  become: true

- name: Install Kubernetes master
  ansible.builtin.command: kubeadm init --config {{ kubeadm_config_dir }}/kubeadm_master_config.yml
  args:
    creates: /etc/kubernetes/kubelet.conf
  register: kubeadm
  become: true

- ansible.builtin.debug:
    var: kubeadm.stdout_lines
  when: kubeadm is changed

- name: Ensure that the /root/.kube directory exists
  ansible.builtin.file:
    dest: /root/.kube
    state: directory
    mode: '0755'
  become: true

- name: Copy Kubernetes admin credentials
  ansible.builtin.command: cp /etc/kubernetes/admin.conf /root/.kube/config
  args:
    creates: /root/.kube/config
  become: true
