# DataVolume lays down the QCOW2 raw image on the file system.
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.usePopulator: "true"
  labels:
    alerts.k8s.io/KubePersistentVolumeFillingUp: disabled
  name: example-rootdisk
  namespace: kubevirt-migrate-target
spec:
  source:
    blank: {}
  storage:
    storageClassName: nfs-csi
    resources:
      requests:
        storage: 10Gi
    volumeMode: Filesystem
