# Apply this resource to the source OpenShift cluster.
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceMigration
metadata:
  name: example-source
  namespace: kubevirt-migrate-source
spec:
  sendTo:
    # If you are migrating within a single cluster, then the synchronization
    # controller is located on this cluster.
    #
    # Conversely, if you are migrating to a different OpenShift clusters, then
    # the synchronization controller configured here is the one in the target
    # cluster. Both clusters must be attached to the same migration network
    # configured in hyperconverged.spec.liveMigrationConfig.network.
    # The virt-handler pods in the source cluster must be able to reach the IP
    # of the synchronization controller in the target cluster via this
    # migration network.
    #
    # In the target cluster, identify the current leader among the
    # synchronization controllers:
    #
    # $ virtsync=$(oc get leases.coordination.k8s.io -n openshift-cnv virt-synchronization-controller -o jsonpath='{.spec.holderIdentity}')
    #
    # If you are migrating within a single cluster, get the Pod IP of the
    # synchronization controller. Use this IP in the connectURL below:
    #
    # $ oc get po -n openshift-cnv $virtsync -o jsonpath='{.status.podIP}'
    #
    # If you are migrating to a different cluster, get the IP of the
    # synchronization controller in the target cluster. The IP is not the pod
    # IP but the IP of the Multus interface migration0 attached to the
    # migration network. Use this IP in the connectURL below. Execute this
    # command on the target cluster to display the Multus IP:
    #
    # $ oc get po -n openshift-cnv $virtsync -o jsonpath='{.metadata.annotations.k8s\.v1\.cni\.cncf\.io/network-status}'
    #
    connectURL: 192.168.78.101:9185
    migrationID: example1
  vmiName: example
