# Apply this resource to the target OpenShift cluster.
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstanceMigration
metadata:
  name: example-target
  namespace: kubevirt-migrate-target
spec:
  receive:
    migrationID: example1
  vmiName: example
