- name: Retrieve CephFS volume {{ cephlab_cephfs_volume_name }}
  block:
    - name: Attempt to retrieve CephFS volume
      ansible.builtin.command: >-
        ceph fs volume info {{ cephlab_cephfs_volume_name }}
      changed_when: false
      become: true

  rescue:
    - name: Create CephFS volume if doesn't exist
      ansible.builtin.import_tasks: cephfs_create_subtasks.yml
