- name: Create node-exporter spec file
  ansible.builtin.template:
    src: node-exporter-spec.yaml
    dest: '{{ cephlab_conf_dir }}/node-exporter-spec.yaml'
    backup: true
    mode: '0644'
  register: cephlab_nodeexporter_spec_result

- name: Apply node-exporter spec
  ansible.builtin.command: >-
    ceph orch apply -i {{ cephlab_conf_dir }}/node-exporter-spec.yaml
  when: cephlab_nodeexporter_spec_result is changed
  become: true
