- name: Retrieve rbd pool {{ cephlab_rbd_pool_name }}
  block:
    - name: Attempt to retrieve rbd pool stats
      ansible.builtin.command: >-
        ceph osd pool stats {{ cephlab_rbd_pool_name }}
      changed_when: false
      become: true

  rescue:
    - name: Create rbd volume if doesn't exist
      ansible.builtin.import_tasks: rbd_create_subtasks.yml
