- name: Retrieve zone {{ cephlab_rgw_store_zone }}
  block:
    - name: Attempt to retrieve zone info
      ansible.builtin.command: >-
        radosgw-admin zone get --rgw-zone {{ cephlab_rgw_store_zone }}
      changed_when: false
      become: true

  rescue:
    - name: Deploy zone if doesn't exist
      ansible.builtin.import_tasks: rgw_deploy_subtasks.yml

- name: Create rgw spec file
  ansible.builtin.template:
    src: rgw-spec.yaml
    dest: '{{ cephlab_conf_dir }}/rgw-{{ cephlab_rgw_store_zone }}-spec.yaml'
    backup: true
    mode: '0644'
  register: cephlab_rgw_spec_result

- name: Apply rgw spec
  ansible.builtin.command: >-
    ceph orch apply -i {{ cephlab_conf_dir }}/rgw-{{ cephlab_rgw_store_zone }}-spec.yaml
  when: cephlab_rgw_spec_result is changed
  become: true

- name: Disable RGW certificate verification in dashboard
  ansible.builtin.command: >-
    ceph dashboard set-rgw-api-ssl-verify false
  when: cephlab_rgw_spec_result is changed
  become: true
