- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
  become: true

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
  become: true
