- name: Check if rosa command is available
  block:
    - name: Attempt to run rosa command
      ansible.builtin.command: rosa help
      changed_when: false

  rescue:
    - ansible.builtin.fail:
        msg: "You must install rosa executable and add it to your $PATH"
