- name: Get Terraform info
  block:
    - name: Attempt to get Terraform version
      ansible.builtin.command: terraform -version
      changed_when: false
      register: common_tasks_terraform_check_result

  rescue:
    - name: Handle failure
      ansible.builtin.fail:
        msg: "You must install Terraform and add it to your $PATH"

- name: Show Terraform info
  ansible.builtin.debug:
    var: common_tasks_terraform_check_result.stdout_lines
