- ansible.builtin.import_tasks: cluster_nodes_deploy.yml
  tags: odf_cluster_nodes

- ansible.builtin.import_tasks: operator_deploy.yml
  tags: odf_operator

- ansible.builtin.import_tasks: cluster_nodes_check.yml
  tags: odf_instance

- ansible.builtin.import_tasks: internal_instance_deploy.yml
  tags: odf_instance
