apiVersion: v1
metadata:
  name: {{ osclusterinstall_info.cluster_name }}
baseDomain: {{ osclusterinstall_info.base_domain }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ osclusterinstall_info.control_plane_replicas }}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: {{ osclusterinstall_info.data_plane_replicas }}
networking:
  clusterNetwork:
  - cidr: {{ osclusterinstall_info.cluster_network_cidr }}
    hostPrefix: 23
  machineNetwork:
  - cidr: {{ osclusterinstall_info.machine_network_cidr }}
  networkType: {{ osclusterinstall_info.network_type }}
  serviceNetwork:
  - {{ osclusterinstall_info.service_network_cidr }}
platform:
{% if osclusterinstall_info.control_plane_replicas == 1 %}
  none: {}
{% else %}
  baremetal:
    apiVIP: {{ osclusterinstall_info.api_vip }}
    ingressVIP: {{ osclusterinstall_info.ingress_vip }}
    loadBalancer:
      type: {{ osclusterinstall_info.load_balancer }}
    provisioningNetwork: Disabled
{% endif %}
{% if osclusterinstall_info.clusterwide_proxy | default({}) %}
proxy:
  httpProxy: {{ osclusterinstall_info.clusterwide_proxy.http_proxy }}
  httpsProxy: {{ osclusterinstall_info.clusterwide_proxy.https_proxy }}
  noProxy: {{ osclusterinstall_info.clusterwide_proxy.no_proxy }}
{% endif %}
pullSecret: '{{ redhat_cloud_pull_secret }}'
sshKey: '{{ osclusterinstall_info.ssh_authorized_key }}'
{% if osclusterinstall_info.trusted_ca_bundle | default('') %}
additionalTrustBundle: |
  {{ osclusterinstall_info.trusted_ca_bundle | indent(2) }}
{% endif %}
