- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for Quay to come up
  ansible.builtin.uri:
    url: 'https://{{ quay_instance_route.resources.0.spec.host }}/api/v1/discovery'
    method: GET
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- name: Report success
  ansible.builtin.set_fact:
    msg: |
      Red Hat Quay installed successfully. Use your browser to access the Quay Web UI and create account for user admin.

      You can browse to:
      https://{{ quay_instance_route.resources.0.spec.host }}

- ansible.builtin.debug:
    msg: "{{ msg.split('\n') }}"
