- name: Copy CA certificate to trust store
  ansible.builtin.copy:
    content: '{{ machinebase_import_ca_certificate }}'
    dest: >-
      {{ (ansible_facts.os_family == 'RedHat') | ternary('/etc/pki/ca-trust/source/anchors', '/usr/local/share/ca-certificates') }}/ansible_ca_cert.crt
  register: machinebase_certificate_result
  become: true

- name: Update trusted CA store (RedHat)
  ansible.builtin.command: update-ca-trust extract
  when:
    - machinebase_certificate_result is changed
    - ansible_facts.os_family == 'RedHat'
  become: true

- name: Update trusted CA store (Debian)
  ansible.builtin.command: update-ca-certificates
  when:
    - machinebase_certificate_result is changed
    - ansible_facts.os_family == 'Debian'
  become: true
