- name: Install chrony package
  ansible.builtin.package:
    name: '{{ item }}'
    state: present
  loop:
    - chrony
  become: true

- name: Enable chronyd service and start it
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  become: true

- name: Refresh Ansible's ansible_date_time fact
  ansible.builtin.setup:
    filter: ansible_date_time
