- name: Check if password expiration for the current user has been disabled
  block:
    - name: Get password expiration for the current user
      ansible.builtin.shell: set -o pipefail && chage -l {{ ansible_facts.user_id }} | grep 99999
      changed_when: false
      become: true

  rescue:
    - name: Disable password expiration for the current local user
      ansible.builtin.command: chage -I -1 -m 0 -M 99999 -E -1 {{ ansible_facts.user_id }}
      become: true
