- name: Configure passwordless sudo
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: configure_passwordless_sudo.yml

- name: Subscribe RHEL
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: subscribe_rhel.yml
  when:
    - ansible_facts.distribution == "RedHat"

- ansible.builtin.import_tasks: configure_proxy.yml
  when:
    - ansible_facts.distribution == "RedHat"
    - machine_base_http_proxy[ansible_facts.domain] is defined

- ansible.builtin.import_tasks: disable_password_expiration.yml

- ansible.builtin.import_tasks: set_ssh_authorized_keys.yml

- ansible.builtin.import_tasks: generate_ssh_keys.yml

- name: Set timezone to {{ machine_base_timezone }}
  community.general.timezone:
    name: '{{ machine_base_timezone }}'
  when: machine_base_timezone | length > 0
  become: true

- ansible.builtin.import_tasks: configure_ntp.yml

- ansible.builtin.import_tasks: configure_fstrim.yml

- ansible.builtin.import_tasks: display_boot.yml
  when:
    - ansible_facts.distribution == "RedHat"
    - ansible_facts.distribution_major_version | int <= 8

- ansible.builtin.import_tasks: fix_hostname.yml

- ansible.builtin.import_tasks: enable_core_dump.yml

- name: Install tools
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: install_tools.yml

- name: Upgrade all packages
  ansible.builtin.import_role:
    name: common_tasks
    tasks_from: upgrade_all_packages.yml
