- ansible.builtin.set_fact:
    mcemanagedcluster_info: '{{ mcemanagedcluster_agent }}'

- ansible.builtin.import_tasks: common/rhacm_detect.yml

- ansible.builtin.import_tasks: common/prereqs_deploy.yml

- ansible.builtin.set_fact:
    mcemanagedcluster_control_plane_agents: >-
      {{ mcemanagedcluster_info.cluster_nodes_individual.values() | selectattr('role', 'equalto', 'master') | length }}
    mcemanagedcluster_worker_agents: >-
      {{ mcemanagedcluster_info.cluster_nodes_individual.values() | selectattr('role', 'equalto', 'worker') | length }}

- ansible.builtin.fail:
    msg: user_managed_networking must be set to true when deploying SNO
  when:
    - mcemanagedcluster_control_plane_agents | int == 1
    - mcemanagedcluster_worker_agents | int == 0
    - mcemanagedcluster_info.user_managed_networking == false

- ansible.builtin.import_role:
    name: openshift_multicluster_engine_infraenv
    tasks_from: deploy.yml
  vars:
    mceinfraenv_info: '{{ mcemanagedcluster_agent }}'

- ansible.builtin.import_role:
    name: openshift_hashicorp_vault
    tasks_from: secret_insert.yml
  vars:
    hvault_mount_point: autogitops
    hvault_secret_name: '{{ oscommon_cluster_domain }}/mce/managed-cluster/{{ mcemanagedcluster_info.cluster_name }}/pull-secret'
    hvault_secret_data:
      .dockerconfigjson: '{{ redhat_cloud_pull_secret }}'

- ansible.builtin.import_role:
    name: openshift_autogitops
    tasks_from: app_deploy.yml
  vars:
    autogitops_app_src_path: templates/agent/managed-cluster
    autogitops_app_dst_path: mce/managed-cluster/{{ mcemanagedcluster_info.cluster_name }}
    autogitops_app_namespace: '{{ mcemanagedcluster_info.cluster_name }}'

- name: Retrieve deployment agents
  kubernetes.core.k8s_info:
    api_version: agent-install.openshift.io/v1beta1
    kind: Agent
    namespace: '{{ mcemanagedcluster_info.cluster_name }}-infraenv'
  register: mcemanagedcluster_agent_result

- name: Bind host to the cluster
  kubernetes.core.k8s:
    definition:
      apiVersion: agent-install.openshift.io/v1beta1
      kind: Agent
      metadata:
        name:  '{{ item.metadata.name }}'
        namespace: '{{ item.metadata.namespace }}'
      spec:
        approved: true
        clusterDeploymentName:
          name: '{{ mcemanagedcluster_info.cluster_name }}'
          namespace: '{{ mcemanagedcluster_info.cluster_name }}'
        role: '{{ mcemanagedcluster_info.cluster_nodes_individual[item.status.inventory.hostname].role }}'
  when: mcemanagedcluster_info.cluster_nodes_individual[item.status.inventory.hostname] is defined
  loop: '{{ mcemanagedcluster_agent_result.resources }}'
  loop_control:
    label: '{{ item.metadata.name }}: {{ item.status.inventory.hostname }} -> {{ mcemanagedcluster_info.cluster_nodes_individual[item.status.inventory.hostname].role | default ("") }}'

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for cluster requirements to be met
  kubernetes.core.k8s_info:
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: '{{ mcemanagedcluster_info.cluster_name }}'
    namespace: '{{ mcemanagedcluster_info.cluster_name }}'
    wait: true
    wait_condition:
      type: RequirementsMet
    wait_sleep: 10
    wait_timeout: 600

- name: Waiting since {{ now(fmt="%I:%M:%S %p") }} for agent cluster installation to finish
  kubernetes.core.k8s_info:
    api_version: extensions.hive.openshift.io/v1beta1
    kind: AgentClusterInstall
    name: '{{ mcemanagedcluster_info.cluster_name }}'
    namespace: '{{ mcemanagedcluster_info.cluster_name }}'
    wait: true
    wait_condition:
      type: Stopped
    wait_sleep: 10
    wait_timeout: 5400
  register: mcemanagedcluster_agentclusterinstall_result

- ansible.builtin.assert:
    that: >-
      mcemanagedcluster_agentclusterinstall_result | json_query('resources[0].status.conditions[?type==`Failed`].status | [0]') == 'False'
    fail_msg: >-
      Agent cluster installation of {{ mcemanagedcluster_info.cluster_name }} failed. Check the AgentClusterInstall resource status for details.
    quiet: true

- ansible.builtin.import_tasks: common/report_success.yml
