{% if vso_vault_connection_trusted_ca_cert %}
kind: Secret
apiVersion: v1
metadata:
  name: trusted-ca-cert
  namespace: vault-secrets-authconfig
stringData:
  ca.crt: |
    {{ vso_vault_connection_trusted_ca_cert | indent(4) }}
{% endif %}
